export const DELETE_CHAT = 'DELETE_CHAT';
export const ADD_CHAT = 'ADD_CHAT';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_NEW_CHAT_TO_MESSAGE_LIST = 'ADD_NEW_CHAT_TO_MESSAGE_LIST'; // for messageList store
export const DELETE_ALL_MESSAGE_FROM_CHAT = 'DELETE_ALL_MESSAGE_FROM_CHA';

export const GET_POSTS = 'GET_POSTS'
export const LOADING_POSTS = 'LOADING_POSTS';
export const ERROR_POSTS = 'ERROR_POSTS';

export const REGISTER_START ='REGISTER_START';
export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_ERROR ='REGISTER_ERROR';

export const LOGIN_START ='LOGIN_START';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_ERROR ='LOGIN_ERROR';

export const LOGOUT_START ='LOGOUT_START';
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS';
export const LOGOUT_ERROR ='LOGOUT_ERROR';