export const DELETE_CHAT = 'DELETE_CHAT';
export const ADD_CHAT = 'ADD_CHAT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_NEW_CHAT_TO_MESSAGE_LIST = 'ADD_NEW_CHAT_TO_MESSAGE_LIST'; // for messageList store
export const DELETE_ALL_MESSAGE_FROM_CHAT = 'DELETE_ALL_MESSAGE_FROM_CHA';